'''
File: wordgame.py
Authors: estrella_margerum
Description:
Implements a word guessing game similar to Hangman
'''

# Import statement: DO NOT delete these! DO NOT write code above this!
import random
import string
import hangman

# -----------------------------------
# Helper code
# (you don't need to understand this helper code)
# Import words for the game

WORDLIST_FILENAME = "words.txt"

def load_words():
    """
    Returns a list of valid words. Words are strings of lowercase letters.
    
    Depending on the size of the word list, this function may
    take a while to finish.
    """
    print "Loading word list from file..."
    # infile: file
    infile = open(WORDLIST_FILENAME, 'r')
    # line: string
    line = infile.read()
    # wordlist: list of strings
    wordlist = line.split()
    print "  ", len(wordlist), "words loaded."
    print 'Type play_wordgame() and press Enter to play a game!'
    return wordlist

# load the dictionary of words and point to it with 
# the words_dict variable so that it can be accessed from anywhere
# in the program
words_dict = load_words()


# Run get_word() within your program to generate a random secret word
# by using a line like this within your program:
# secret_word = get_word()

def get_word():
    """
    Returns a random word from the word list
    """
    word=words_dict[random.randrange(0,len(words_dict))]
    return word

# end of helper code
# -----------------------------------

def playmode():
    '''
    Allows user to select level of difficulty
    Returns MAX_GUESSES for later use in program
    '''
    while True:
        level = raw_input("Please select a level of difficulty (Easy/Medium/Hard): ")  
        if level == 'Easy':
            MAX_GUESSES = 12
            break
        elif level == 'Medium':
            MAX_GUESSES = 9
            break
        elif level == 'Hard':
            MAX_GUESSES = 6
            break
        else:
            print "Please choose between Easy/Medium/Hard"
    return MAX_GUESSES

def print_guessed(secret_word, letters_guessed):
    '''
    Receives two string arguments called secret_word and letters_guessed
    Returns a string which is the string secret_word with a dash used
    to replace each character that has not yet been guessed by the player  
    '''

    # Adds a space for neatness
    print ""
    alpha = string.lowercase[:26]
    print "Letters not guessed yet: "
    print alpha.translate(None, letters_guessed)
    
    word_so_far = ''
    # fill word_so_far with letters correctly guessed and the rest with " _ "
    for c in secret_word:
        if c in letters_guessed:
            word_so_far = word_so_far + c
        else:
            word_so_far = word_so_far + ' _ '
            
    return word_so_far


def play_wordgame():
    """
    Combines all functions and allows user to play guessing word game
    until success or failure
    """
    # play the game
    secret_word = get_word()
    # change this to secret_word=get_word() when you are ready to start playing
    # with random words generated by the program

    max_guesses = playmode()

    guesses_made = 0    # number of guesses made
    letters_guessed = "" # letters already guessed
    word_sofar = "" # appearance of the word so far
    # change variable to initial value

    # game start
    print"Welcome, game start"
    print "I am thinking of a word that is", len(secret_word), "letters long"
    
 
    while True:
        
        if word_sofar == secret_word:
            print "Correct, you win the game!"
            break
            #user wins
        
        elif guesses_made < max_guesses:
            print"There are", max_guesses - guesses_made, "guesses left."
            letter = raw_input("Please enter a letter, \
or the word 'guess' to try and guess the full word: ")
            letter = letter.lower()
            #establish initial guessing format
            
            while True:
                if letters_guessed.find(letter)!=-1:
                    # check if input letter is in letters_guessed already
                    print ""
                    print "That letter has been entered already. Please enter a \
                            new letter."
                    break
                    # prevent letters from being guessed more than once

                if letter == 'guess':
                    print"Please guess the", len(secret_word), "letter word"
                    full_word = raw_input("Enter the full word: ")
                    if full_word == secret_word:
                        print "Correct, you win the game!"
                        return
                    else:
                        print ""
                        print "Sorry, that is not the word I am thinking of"
                        guesses_made = guesses_made + 2
                        break
                    
                if len(letter) != 1:
                    print 'Please enter one letter'
                    break
                    
                else:
                    letters_guessed = letters_guessed + letter
                    word_sofar = print_guessed(secret_word, letters_guessed)
                    #reveal correctly guessed letters in secret_word
                    #adjust remaining amount of guesses

                    if letter in secret_word:
                        print "Good guess: ",word_sofar
                        break
                        #continue guessing after correct guess
##                    
                    else:
                        guesses_made = guesses_made + 1
                        print "Oops! That letter is not in my word: ",word_sofar
                        if max_guesses == 12:
                            if guesses_made == 2 or guesses_made ==3:
                                print hangman.hangman[1]
                            elif guesses_made == 4 or guesses_made ==5:
                                print hangman.hangman[2]
                            elif guesses_made == 6 or guesses_made ==7:
                                print hangman.hangman[3]
                            elif guesses_made == 8 or guesses_made ==9:
                                print hangman.hangman[4]
                            elif guesses_made == 10 or guesses_made ==11:
                                print hangman.hangman[5]
                            elif guesses_made == 12:
                                print hangman.hangman[6]
                            else:
                                print hangman.hangman[0]
                        elif max_guesses == 9:
                            if guesses_made == 1 or guesses_made ==2:
                                print hangman.hangman[1]
                            elif guesses_made == 3 or guesses_made ==4:
                                print hangman.hangman[2]
                            elif guesses_made == 5 or guesses_made ==6:
                                print hangman.hangman[3]
                            elif guesses_made == 7 or guesses_made ==8:
                                print hangman.hangman[5]
                            elif guesses_made == 9:
                                print hangman.hangman[6]
                            else:
                                print hangman.hangman[0]
                        else:
                            if guesses_made == 1:
                                print hangman.hangman[1]
                            elif guesses_made == 2:
                                print hangman.hangman[2]
                            elif guesses_made == 3:
                                print hangman.hangman[3]
                            elif guesses_made == 4:
                                print hangman.hangman[4]
                            elif guesses_made == 5:
                                print hangman.hangman[5]
                            elif guesses_made == 6:
                                print hangman.hangman[6]
                            else:
                                print hangman.hangman[0]
                        break
                        #continue guessing after incorrect guess
    
        else:
            print "Sorry, you lose. The word I am thinking of is", secret_word
            break
            #user loses
            
    return None

    
