''' File: wordgame.py Authors: put your last names here Description:
Implements a word guessing game similar to Hangman '''

# Import statement: DO NOT delete these! DO NOT write code above this!
import random

# -----------------------------------
# Helper code
# (you don't need to understand this helper code)
# Import words for the game

WORDLIST_FILENAME = "words.txt"

def load_words():
    """
    Returns a list of valid words. Words are strings of lowercase letters.
    
    Depending on the size of the word list, this function may
    take a while to finish.
    """
    print "Loading word list from file..."
    # infile: file
    infile = open(WORDLIST_FILENAME, 'r')
    # line: string
    line = infile.read()
    # wordlist: list of strings
    wordlist = line.split()
    print "  ", len(wordlist), "words loaded."
    print 'Type play_wordgame() and press Enter to play a game!'
    return wordlist

# load the dictionary of words and point to it with 
# the words_dict variable so that it can be accessed from anywhere
# in the program
words_dict = load_words()


# Run get_word() within your program to generate a random secret word
# by using a line like this within your program:
# secret_word = get_word()

def get_word():
    """
    Returns a random word from the word list
    """
    word=words_dict[random.randrange(0,len(words_dict))]
    return word

# end of helper code
# -----------------------------------


# CONSTANTS
MAX_GUESSES = 12


def print_guessed(secret_word, letters_guessed):
    '''
    Receives two string arguments called secret_word and letters_guessed
    Returns a string which is the string secret_word with a dash used
    to replace each character that has not yet been guessed by the player  
    '''

    word_so_far = ''
    
    for c in secret_word:
        if c in letters_guessed:
            word_so_far = word_so_far + c
        else:
            word_so_far = word_so_far + ' _ '

    return word_so_far



def play_wordgame():
    """
    Combines all functions and allows user to play guessing word game
    until success or failure
    """
    # play the game
    secret_word = get_word()
    #change this to secret_word=get_word() when you are ready to start playing
    #with random words generated by the program

    guesses_made = 0

    print"Welcome, game start"
    print "I am thinking of a word that is", len(secret_word), "letters long"
    
    letters_guessed = ""
    word_sofar = ""
   #changed variable to type str
    while True:
        
        if word_sofar == secret_word:
            print "Correct, you win the game!"
            break
     #this statement appears after user wins   
        elif guesses_made < MAX_GUESSES:
            print"There are", MAX_GUESSES - guesses_made, "guesses left."
            letter = raw_input("Please guess a letter: ")
            letter = letter.lower()
     #this section establishes the initial guessing format
            while True:
                if letters_guessed.find(letter)!=-1:
                    #this checks if the input letter is in letters_guessed already
                    print"That letter has been entered already. Please enter a \
                            new letter."
                    break
                #this section prevents letters from being guessed more than once
                else:
                    guesses_made = guesses_made + 1
                    letters_guessed = letters_guessed + letter
                    word_sofar = print_guessed(secret_word, letters_guessed)
                    #this reveals correctly guessed letters in the secret_word and
                    #adjusts remaining amount of guesses
                    if letter in secret_word:
                        print "Good guess: ",word_sofar
                        break
                    #continues guessing after correct guess
                    else:
                        print "Oops! That letter is not in my word: ",word_sofar
                        break
                    #continues guessing after incorrect guess
    
        else:
            print "Sorry, you lose. The word I am thinking of is", secret_word
            break
        #message that appears after losing the game
            
    return None

    
